### ISSUE TITLE
Web site doesn't make it clear what license applies to its content (if any)

### ISSUE THREAD

**Issue by fghaas** [murat1985/murat1985.github.io#1]
Hi, it seems that your web site (and this GitHub repo) are missing licensing information so it's not clear whether you're OK with your content being quoted or otherwise used by people building slides or talk material incorporating some of your writings. May I suggest that you add a LICENSE file to your repo? I use [CC-BY](https://creativecommons.org/licenses/by/4.0/) or [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) for just about anything I write that isn't code (though I'm clearly biased towards CC licenses), would you consider doing the same?

**Comment by logingood** [comment]
Hi @fghaas sorry haven't noticed this issue. I've added CC license and MIT license for repository itself, thank you for the hint.

**Comment by fghaas** [comment]
Thanks!
